services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/internship-api
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env.local'
      - '.env.test.local'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres:
