default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  database: internship_api_development

test:
  <<: *default
  database: internship_api_test

production:
  <<: *default
  database: internship_api_production
